# Jekyll configuration
excerpt_separator: <!--more-->
theme: minima
plugins:
  - jekyll-feed

# GitHub page configuration
domain: xballoy.github.io
url: https://xballoy.github.io

# Site configuration
lang: en
title: Xavier Balloy Dev Blog
author: Xavier Balloy
description: >-
  I write things about dev, mostly in English but sometimes in French.

# minima configuration
twitter_username: xballoy
linkedin_username: xavierballoy
github_username: xballoy
show_excerpts: true
fathom_analytics:
  site_id: XPSDARMZ
